
VERBOSE = True
DETAILS_JSON_FILENAME = "details.json"
CHANNEL_PRESENCE_MATRIX_FILENAME = "channels_presence_mtx.csv"
LOGICOL_PRE_OVERLAP_RESOLVE_FILENAME = "logicol_mtx.csv"
LOGICOL_POST_OVERLAP_RESOLVE_FILENAME = "logicol_mtx_TRIMMED.csv"

#SEGMENTS_MTX_FILENAME = "segments_mtx.csv"
